parameters:
#    material.example.class: Gestor\MaterialBundle\Example

services:
#    material.example:
#        class: %material.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
