adjudicatario_index:
    pattern:  /
    defaults: { _controller: "GestionBundle:infoTipoAdjudicatario:index" }

adjudicatario_new:
    pattern:  /nuevo
    defaults: { _controller: "GestionBundle:infoTipoAdjudicatario:new" }

adjudicatario_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "GestionBundle:infoTipoAdjudicatario:edit" }