mobiliario_index:
    pattern:  /
    defaults: { _controller: "GestionBundle:infoTipoMobiliario:index" }

mobiliario_new:
    pattern:  /nuevo
    defaults: { _controller: "GestionBundle:infoTipoMobiliario:new" }

mobiliario_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "GestionBundle:infoTipoMobiliario:edit" }
