informatica_index:
    pattern:  /
    defaults: { _controller: "GestionBundle:infoTipoInformatica:index" }

informatica_new:
    pattern:  /nuevo
    defaults: { _controller: "GestionBundle:infoTipoInformatica:new" }

informatica_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "GestionBundle:infoTipoInformatica:edit" }

informatica_update:
    pattern:  /{id}/actualizar
    defaults: { _controller: "GestionBundle:infoTipoInformatica:update" }
    requirements: { _method: post|put }
