empresa_index:
    pattern:  /
    defaults: { _controller: "GestionBundle:infoTipoEmpresa:index" }

empresa_new:
    pattern:  /nuevo
    defaults: { _controller: "GestionBundle:infoTipoEmpresa:new" }

empresa_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "GestionBundle:infoTipoEmpresa:edit" }

empresa_update:
    pattern:  /{id}/actualizar
    defaults: { _controller: "GestionBundle:infoTipoEmpresa:update" }
    requirements: { _method: post|put }
