operativo_index:
    pattern:  /
    defaults: { _controller: "GestionBundle:infoTipoOperativo:index" }

operativo_new:
    pattern:  /nuevo
    defaults: { _controller: "GestionBundle:infoTipoOperativo:new" }

operativo_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "GestionBundle:infoTipoOperativo:edit" }

operativo_update:
    pattern:  /{id}/actualizar
    defaults: { _controller: "GestionBundle:infoTipoOperativo:update" }
    requirements: { _method: post|put }
