parameters:
#    mensaje.example.class: Gestor\MensajeBundle\Example

services:
#    mensaje.example:
#        class: %mensaje.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
