Gestor\MensajeBundle\Entity\Mensaje:
    type: entity
    table: null
    repositoryClass: Gestor\MensajeBundle\Entity\MensajeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fkusuario:
            type: integer
        fecha:
            type: datetime
        mensaje:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
